# Generated by Django 4.1.7 on 2023-04-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_product', models.CharField(max_length=70)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=120)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
